#!/usr/bin/env python3
"""
Central version metadata helpers for BinaryKeyboard.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
VERSIONS_FILE = PROJECT_ROOT / "config" / "versions.json"


def _split_semver(value: str) -> tuple[int, int, int]:
    parts = [int(part, 10) for part in value.strip().split(".")]
    if len(parts) != 3:
        raise ValueError(f"Expected semver 'x.y.z', got: {value}")
    return (parts[0], parts[1], parts[2])


def _split_minor_version(value: str) -> tuple[int, int]:
    parts = [int(part, 10) for part in value.strip().split(".")]
    if len(parts) != 2:
        raise ValueError(f"Expected minor version 'x.y', got: {value}")
    return (parts[0], parts[1])


def load_versions() -> dict[str, Any]:
    return json.loads(VERSIONS_FILE.read_text(encoding="utf-8"))


def product_version() -> str:
    return str(load_versions()["product"]["version"])


def firmware_meta(chip: str) -> dict[str, Any]:
    chip_key = chip.strip().upper()
    try:
        return load_versions()["firmware"][chip_key]
    except KeyError as exc:
        raise KeyError(f"Unknown firmware chip family: {chip}") from exc


def firmware_version(chip: str) -> str:
    return str(firmware_meta(chip)["firmware_version"])


def protocol_family(chip: str) -> str:
    return str(firmware_meta(chip)["protocol_family"])


def protocol_version(chip: str) -> str:
    return str(firmware_meta(chip)["protocol_version"])


def storage_version(chip: str) -> str:
    return str(firmware_meta(chip)["storage_version"])


def legacy_compat_version(chip: str) -> int:
    meta = firmware_meta(chip)
    return int(meta.get("legacy_compat_version", 0))


def emit_c_header(chip: str, out: Path) -> None:
    chip_key = chip.strip().upper()
    fw_major, fw_minor, fw_patch = _split_semver(firmware_version(chip_key))
    proto_major, proto_minor = _split_minor_version(protocol_version(chip_key))
    storage_major, storage_minor = _split_minor_version(storage_version(chip_key))
    compat_version = legacy_compat_version(chip_key)

    lines = [
        "/* Auto-generated by tools/scripts/versioning.py. Do not edit manually. */",
        "#ifndef BK_VERSION_CONFIG_H",
        "#define BK_VERSION_CONFIG_H",
        "",
        f"#define BK_CHIP_FAMILY \"{chip_key}\"",
        f"#define BK_FIRMWARE_VERSION_MAJOR {fw_major}",
        f"#define BK_FIRMWARE_VERSION_MINOR {fw_minor}",
        f"#define BK_FIRMWARE_VERSION_PATCH {fw_patch}",
        f"#define BK_PROTOCOL_FAMILY \"{protocol_family(chip_key)}\"",
        f"#define BK_PROTOCOL_VERSION_MAJOR {proto_major}",
        f"#define BK_PROTOCOL_VERSION_MINOR {proto_minor}",
        f"#define BK_STORAGE_VERSION_MAJOR {storage_major}",
        f"#define BK_STORAGE_VERSION_MINOR {storage_minor}",
        f"#define BK_LEGACY_COMPAT_VERSION {compat_version}",
        "",
        "#endif",
        "",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def emit_ts_module(out: Path) -> None:
    versions = load_versions()
    product = str(versions["product"]["version"])
    firmware = versions["firmware"]

    def to_ts_meta(chip_key: str) -> str:
        meta = firmware[chip_key]
        fw_major, fw_minor, fw_patch = _split_semver(str(meta["firmware_version"]))
        proto_major, proto_minor = _split_minor_version(str(meta["protocol_version"]))
        storage_major, storage_minor = _split_minor_version(str(meta["storage_version"]))
        return (
            f"  {chip_key}: {{\n"
            f"    chipFamily: '{chip_key}',\n"
            f"    firmwareVersion: {{ major: {fw_major}, minor: {fw_minor}, patch: {fw_patch} }},\n"
            f"    protocolFamily: '{meta['protocol_family']}',\n"
            f"    protocolVersion: {{ major: {proto_major}, minor: {proto_minor} }},\n"
            f"    storageVersion: {{ major: {storage_major}, minor: {storage_minor} }},\n"
            f"  }},"
        )

    lines = [
        "/* Auto-generated by tools/scripts/versioning.py. Do not edit manually. */",
        "export const PRODUCT_VERSION = " + json.dumps(product) + ";",
        "",
        "export const FIRMWARE_VERSION_META = {",
        to_ts_meta("CH592F"),
        to_ts_meta("CH552G"),
        "} as const;",
        "",
        "export type FirmwareChipFamily = keyof typeof FIRMWARE_VERSION_META;",
        "",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tools/scripts/versioning.py")
    sub = parser.add_subparsers(dest="command", required=True)

    p_show = sub.add_parser("show", help="Print version metadata")
    p_show.add_argument("--chip", choices=("CH592F", "CH552G"))

    p_emit = sub.add_parser("emit-c-header", help="Generate a C header for a chip family")
    p_emit.add_argument("--chip", required=True, choices=("CH592F", "CH552G"))
    p_emit.add_argument("--out", required=True)

    p_emit_ts = sub.add_parser("emit-ts", help="Generate a TypeScript version module")
    p_emit_ts.add_argument("--out", required=True)

    return parser


def main() -> int:
    args = build_parser().parse_args()

    if args.command == "show":
        if args.chip:
            print(json.dumps(firmware_meta(args.chip), indent=2, ensure_ascii=True))
        else:
            print(json.dumps(load_versions(), indent=2, ensure_ascii=True))
        return 0

    if args.command == "emit-c-header":
        emit_c_header(args.chip, Path(args.out))
        return 0

    if args.command == "emit-ts":
        emit_ts_module(Path(args.out))
        return 0

    raise SystemExit(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
