/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BasicKeyboard: typeof import('./src/components/keyboards/BasicKeyboard.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataInfoCard: typeof import('./src/components/DataInfoCard.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeviceFinder: typeof import('./src/components/DeviceFinder.vue')['default']
    DeviceInfoCard: typeof import('./src/components/DeviceInfoCard.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FiveKeysKeyboard: typeof import('./src/components/keyboards/FiveKeysKeyboard.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    KnobKeyboard: typeof import('./src/components/keyboards/KnobKeyboard.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
